### ISSUE TITLE
Can't add to favorite

### ISSUE THREAD

**Issue by xuanvu** [mintsoft/kodi.plugin.video.pluralsight#2] opened 2015-08-22 16:11 UTC
Getting error when try to add a course to Favorite

**Comment by mintsoft** [comment] 2015-08-22 16:35
@xuanvu Thanks for the report; it appears to be working for me on the released version. Could you possible paste the output of the kodi.log with the error in it? Also information about which platform you're running Kodi on would be useful :+1: 

cc @supertom44

**Comment by mintsoft** [comment] 2015-08-31 20:10
@xuanvu Sorry but I can't reproduce this at all. I'm going to close this for now, if you can get us some debugging info then we'll take another look :+1:

**Closed as completed by mintsoft** 2015-08-31 20:10 UTC
Labels: bug
