### ISSUE TITLE
PlayBack Failure

### ISSUE THREAD

**Issue by fclante** [mintsoft/kodi.plugin.video.pluralsight#11] opened 2017-03-11 06:59 UTC
As of yesterday I can no longer play any videos. I can login and browse courses. that's it.

In the kodi.log it Throws a VideoNotFoundError - so the video_url field is never set.

**Comment by mintsoft** [comment] 2017-03-11 20:21
Hi @fclante 
Thanks for the report, I've just confirmed this on my install too. I'll have a crack at it later on today hopefully

**Comment by lestrela** [comment] 2017-03-28 15:02
Any news on this?

Regards
Leo

**Comment by mintsoft** [comment] 2017-03-28 18:59
@lestrela This is bigger than I hoped unfortunately; it looks like a significant portion of Pluralsight's API structured has changed. Hopefully I'll find some time to kick it again soon

**Comment by lestrela** [comment] 2017-03-29 22:11
What a pity! Right now that I was taking my rasp pi all over just to study
at Pluralsight.
Good luck. I hope the problem is simple to fix.
Thanks for the answer!

Cheers!!

Leo

2017-03-28 15:59 GMT-03:00 Rob Emery <notifications@github.com>:

**Comment by mintsoft** [comment] 2017-04-01 12:00
Good news, I've got this working again. I just need to clean the code up then I can release it

**Comment by mintsoft** [comment] 2017-04-02 18:18
Just waiting for KODI to accept the PR (https://github.com/xbmc/repo-plugins/pull/1088) which will release 1.1.3

**Comment by lestrela** [comment] 2017-04-03 22:00
Great Rob!!

Yiu are the man!!!

Em domingo, 2 de abril de 2017, Rob Emery <notifications@github.com>
escreveu:

**Comment by mintsoft** [comment] 2017-04-06 18:54
Fixed in 1.1.3; now released

**Closed as completed by mintsoft** 2017-04-06 18:54 UTC
Labels: bug

**Comment by lestrela** [comment] 2017-04-06 20:45
Great Rob. I'm going to test ASAP


2017-04-06 15:54 GMT-03:00 Rob Emery <notifications@github.com>:

**Comment by lestrela** [comment] 2017-04-07 00:59
Working fine!!! Up and running!!

Regards Rob and thx a lot

Cheers

Leo

Em quinta-feira, 6 de abril de 2017, Leonardo <leonardo.estrela@gmail.com>
escreveu:
